FROM alpine-java:base
MAINTAINER javaonfly
COPY config-service/target/config-service-0.0.1-SNAPSHOT.jar /opt/lib/
RUN mkdir -p /opt/lib/myconfig
COPY myConfig/* /opt/lib/myconfig/
ENV SPRING_APPLICATION_JSON='{"spring": {"cloud": {"config": {"server": {"git": {"uri": "/opt/lib/myconfig"}}}}}}'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/config-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8888
